### PR TITLE
Update to v0.14.0-rc3

### PR DESCRIPTION
**Pull request by JordanMartinez**
Backlinking to purescript-contrib/governance#35

### CODE REVIEW

**Comment by JordanMartinez** [comment]
I'm getting two errors here. The first is likely a dependency issue in the `numbers` repo / `prepare-0.14` package set. The second is a largely issue because the two functions referenced were not ported over to numbers and dropped entirely:
```
[1/2 ModuleNotFound] .spago/numbers/master/src/Data/Number.purs:10:1

  10  import Data.Function.Uncurried (Fn4, runFn4)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  
  Module Data.Function.Uncurried was not found.
  Make sure the source file exists, and that it has been provided as an input to the compiler.

[2/2 ModuleNotFound] src/Data/FormURLEncoded.purs:11:1

  11  import Global (decodeURIComponent, encodeURIComponent)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  
  Module Global was not found.
  Make sure the source file exists, and that it has been provided as an input to the compiler.

           Src   Lib   All
Warnings   0     0     0  
Errors     1     1     2  
[error] Failed to build.
```

**Comment by thomashoneyman** [comment]
This library basically wraps `decodeURIComponent` and `encodeURIComponent`. Since they were removed from `numbers` and `globals` is being deprecated, we can:

- foreign-import them here (and add an `eslint` file and `package.json` as is done for other contrib libraries that use JS), or
- follow https://github.com/purescript/purescript-globals/issues/22#issuecomment-727088955 and create a `js-uri` library within contrib that contains these functions (@garyb, do you have an opinion?)

either way, I don't think we need the dependency on `numbers`.

**Comment by thomashoneyman** [comment]
I say we go ahead and make a tiny `js-uri` library that can be used by this and the other libraries that have needed the `*URIComponent` functions as we update for 0.14.

**Comment by JordanMartinez** [comment]
I don't think the issue is making that repo. It was my understanding that creating the `js-uri` repo was the approach we would be taking. The issue is that no one has created it yet. I assume this should go in `purescript-contrib`, correct?

**Comment by thomashoneyman** [comment]
That's right, we can put it in `contrib`. I don't think anything from `core` relies on it. We can use `contrib-updater` to scaffold the library. I can take care of it if you'd like.

**Comment by JordanMartinez** [comment]
Yeah. Please do!

**Comment by garyb** [comment]
I guess my preference would be to implement the URI codec functions without specifically relying on the FFI functions, as then we're not forcing a dependency on the JS runtime, and we could also make them not terrible :wink:... but maybe that's out of scope for now.

**Comment by JordanMartinez** [comment]
I can't approve this PR because I opened it, but I approve Thomas' commit that fixes the dependency issue. If someone else wants to approve this, we can get it merged.

**Pull request merged**
